name: car_ticket
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3

  # Firebase packages
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  firebase_messaging: ^15.0.3
  firebase_analytics: ^11.2.0

  # Other packages
  equatable: ^2.0.5
  get: ^4.6.6
  shared_preferences: ^2.2.3
  gap: ^3.0.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  uuid: ^4.4.0
  flutter_stripe: ^11.0.0
  # qr_code_scanner: ^1.0.1
  flutter_dotenv: ^5.1.0
  fluttertoast: ^8.2.5
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  file_saver: ^0.2.13 # Make sure this is included
  flutter_svg: ^2.0.8
  pdf: ^3.10.7
  printing: ^5.11.1
  fl_chart: ^0.63.0
  intl: ^0.19.0
  data_table_2: ^2.5.9
  flutter_staggered_animations: ^1.1.1
  animations: ^2.0.7
  shimmer: ^3.0.0
  permission_handler: ^11.0.1
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  mobile_scanner: ^6.0.6

  # HTTP - downgrade to be compatible with gallery_saver
  http: ^1.2.1

  # Use a forked version of gallery_saver that's compatible with http 1.x
  # or use the official version with the downgraded http
  # image_gallery_saver: ^2.0.3
  # gallery_saver: ^2.3.2  # Comment out this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/car_image.png
    - assets/images/excel_coaster.png
    - assets/images/seat 2.svg
    - assets/images/black_car.png
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
